### ISSUE TITLE
调用获取镜像API接口报错：镜像大小超出Integer最大值

### ISSUE THREAD

**Issue by sunkangke** [huaweicloud/huaweicloud-sdk-java-v3#1]
使用SDK调用获取镜像，返回数据中有镜像大小为9056976896的记录，但com.huaweicloud.sdk.ims.v2.model.ImageInfo实体中imageSize字段类型为Integer，提示报错，下面是部分错误日志：

2020-07-06 11:04:13.643  INFO 13308 --- [           main] HuaweiCloud-SDK-Access                   : "GET https://ims.cn-north-4.myhuaweicloud.com/v2/cloudimages?enterprise_project_id=0&__imagetype=gold&visibility=public&limit=500&virtual_env_type=FusionCompute&disk_format=zvhd2&sort_key=id&__isregistered=true&sort_dir=desc" 200 95575 38b44e1df0c9ac9bbf20ca32303969f1
2020-07-06 11:04:13.780 ERROR 13308 --- [           main] c.huaweicloud.sdk.core.utils.JsonUtils   : [Method toObject] Occur Internal Error {}

com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Integer` from String "9056976896": Overflow: numeric value (9056976896) out of range of Integer (-2147483648 - 2147483647)
 at [Source: (StringReader); line: 1, column: 190] (through reference chain: com.huaweicloud.sdk.ims.v2.model.ListImagesResponse["images"]->java.util.ArrayList[0]->com.huaweicloud.sdk.ims.v2.model.ImageInfo["__image_size"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1676) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:932) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer._parseInteger(NumberDeserializers.java:514) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:474) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:452) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.10.2.jar:2.10.2]

**Comment by xionghao-hw** [comment]
多谢反馈，下周版本修复，谢谢

**Comment by xionghao-hw** [comment]
3.0.6-beta版本修复
