### ISSUE TITLE
Problem calling CBR listBackups

### ISSUE THREAD

**Issue by renutz** [huaweicloud/huaweicloud-sdk-java-v3#17]
Simple code using latest 3.0.18-beta:

		CbrClient cbrclient = CbrClient.newBuilder()
				.withCredential(credentials)
				.withHttpConfig(config)
				.withEndpoint("https://cbr." + region + ".myhuaweicloud.com")
				.build();
		ListBackupsRequest requestBackup = new ListBackupsRequest();
		List<BackupResp> backups = cbrclient.listBackups(requestBackup).getBackups();
		Logger.debug(".............. %s", backups.size());
		for (BackupResp backup: backups) {
			Logger.debug(".............. %s", backup.toString());
		}

Get error:

com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (String)"{"count": 1, "backups": [{"provider_id": ....

Note: ListVaultResponse vaults = cbrclient.listVault(request); // it works!

We tried jackson versions 2.7.9.7 and 2.11.3 and both do not work.

**Comment by xionghao-hw** [comment]
Hello, please add some debug code and get the response body for us, thank you.


		CbrClient cbrclient = CbrClient.newBuilder()
					.withCredential(credentials)
			.withHttpConfig(config)
			.withEndpoint("https://cbr." + region + ".myhuaweicloud.com")
			.withHttpConfig(new HttpConfig()
                        .addHttpListener(HttpListener.forResponseListener(responseListener ->
                                logger.info("RESPONSE: {} {} {} {} {}",
                                        responseListener.httpMethod(),
                                        responseListener.uri(),
                                        responseListener.statusCode(),
                                        responseListener.headers().entrySet()
                                                .stream().flatMap(entry ->
                                                entry.getValue().stream().map(value -> entry.getKey() + " : " + value))
                                                .collect(Collectors.joining(";")),
                                        responseListener.body().orElse(""))))
                        .addHttpListener(HttpListener.forRequestListener(requestListener ->
                                logger.info("REQUEST: {} {} {} {}",
                                        requestListener.httpMethod(),
                                        requestListener.uri(),
                                        requestListener.headers().entrySet()
                                                .stream().flatMap(entry ->
                                                entry.getValue().stream().map(value -> entry.getKey() + " : " + value))
                                                .collect(Collectors.joining(";")),
                                        requestListener.body().orElse("")))))
			.build();
		ListBackupsRequest requestBackup = new ListBackupsRequest();
		List<BackupResp> backups = cbrclient.listBackups(requestBackup).getBackups();
		Logger.debug(".............. %s", backups.size());
		for (BackupResp backup: backups) {
			Logger.debug(".............. %s", backup.toString());
		}

**Comment by renutz** [comment]
I changed the tokens and projectid for 'xxxxxx', 'yyyyyy', 'zzzzzzz'

12:15:55,793 DEBUG ~ REQUEST: GET https://cbr.la-south-2.myhuaweicloud.com/v3/xxxxxxx/backups?own_type=private Authorization : SDK-HMAC-SHA256 Access=XVVVVV, SignedHeaders=host;user-agent;x-project-id;x-sdk-date, Signature=yyyyyyy;Host : cbr.la-south-2.myhuaweicloud.com;User-Agent : huaweicloud-usdk-java/3.0;X-Project-Id : xxxxxxx;X-Sdk-Date : 20201023T121555Z 
12:15:57,921 DEBUG ~ RESPONSE: GET https://cbr.la-south-2.myhuaweicloud.com/v3/xxxxxxxx/backups?own_type=private 200 Connection : keep-alive;Content-Length : 1235;Content-Type : application/json;Date : Fri, 23 Oct 2020 12:15:57 GMT;Server : api-gateway;Strict-Transport-Security : max-age=31536000; includeSubdomains;;X-Compute-Request-Id : req-ccb03965-7145-4605-8063-66761fe119d5;X-Content-Type-Options : nosniff;X-Download-Options : noopen;X-Frame-Options : SAMEORIGIN;X-Openstack-Request-Id : req-ccb03965-7145-4605-8063-66761fe119d5;X-Request-Id : yyyyyy;X-XSS-Protection : 1; mode=block; {"count": 1, "backups": [{"provider_id": ".......]}
12:15:57,921 INFO  ~ "GET https://cbr.la-south-2.myhuaweicloud.com/v3/xxxxxxxx/backups?own_type=private" 200 1235 zzzzzz
12:15:57,923 ERROR ~ [Method toObject] Occur Internal Error {}
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (String)"{"count": 1, "backups": [.....
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1216)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1126)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:596)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:207)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:173)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at com.huaweicloud.sdk.core.utils.JsonUtils.toObjectIgnoreUnknown(JsonUtils.java:256)
	at com.huaweicloud.sdk.core.HcClient.extractResponse(HcClient.java:243)
	at com.huaweicloud.sdk.core.HcClient.syncInvokeHttp(HcClient.java:116)
	at com.huaweicloud.sdk.cbr.v1.CbrClient.listBackups(CbrClient.java:181)

12:15:57,925 ERROR ~ can not parse json result to response object
com.huaweicloud.sdk.core.exception.SdkException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token

**Comment by xionghao-hw** [comment]
Hi, we use our own account to test and result is normal. Maybe the server side response body include some unnormal infomation, so we need to check the complete body content. It is recommended to create a ticket on the HUAWEI CLOUD console to handle the problem. Thank you.

**Comment by xionghao-hw** [comment]
Hi, 3.0.19-beta fix this problem, thx.

**Comment by renutz** [comment]
Hi. I confirm 3.0.19 fixed.

Thank you
