### ISSUE TITLE
查询直播中的流信息(ListLiveStreamsOnline)

### ISSUE THREAD

**Issue by xuquanru** [huaweicloud/huaweicloud-sdk-java-v3#30]
查询直播中的流信息(ListLiveStreamsOnline)
返回结果SDK无法解析成类
![image](https://user-images.githubusercontent.com/26319713/111974590-82937d00-8b3a-11eb-8b05-1bbaaff24d7e.png)
异常信息如下：
18:11:53.742 [main] ERROR com.huaweicloud.sdk.core.utils.JsonUtils - [Method toObject] Occur Internal Error {}
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.huaweicloud.sdk.live.v1.model.OnlineInfo` out of START_ARRAY token
 at [Source: (String)"{
 "total_num": 2,
 "total_page": 1,
 "offset": 0,
 "limit": 2,
 "request_id": "1d378f1e-a917-42d7-9ade-ef6de1133093",
 "streams": [
  {
   "publish_domain": "jtspy.gstscc.cn",
   "app": "live",
   "stream": "123456789",
   "start_time": "2021-03-22T09:28:57Z",
   "video_codec": "H264",
   "audio_codec": "AAC",
   "video_frame_rate": 30,
   "audio_frame_rate": 43,
   "video_bitrate": 2454,
   "audio_bitrate": 156,
   "resolution": "1280x720",
   "client_ip": "183.62.48.252"
  },
  {
   "publish_"[truncated 330 chars]; line: 7, column: 13] (through reference chain: com.huaweicloud.sdk.live.v1.model.ListLiveStreamsOnlineResponse["streams"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1468)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1242)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1190)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:604)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:190)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.huaweicloud.sdk.core.utils.JsonUtils.toObjectIgnoreUnknown(JsonUtils.java:256)
	at com.huaweicloud.sdk.core.HcClient.extractResponse(HcClient.java:246)
	at com.huaweicloud.sdk.core.HcClient.syncInvokeHttp(HcClient.java:124)
	at com.huaweicloud.sdk.live.v1.LiveClient.listLiveStreamsOnline(LiveClient.java:93)
	at cn.xqrcloud.huawei.ListLiveStreamsOnlineSolution.main(ListLiveStreamsOnlineSolution.java:41)
18:11:53.742 [main] ERROR com.huaweicloud.sdk.core.HcClient - can not parse json result to response object
com.huaweicloud.sdk.core.exception.SdkException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.huaweicloud.sdk.live.v1.model.OnlineInfo` out of START_ARRAY token
 at [Source: (String)"{
 "total_num": 2,
 "total_page": 1,
 "offset": 0,
 "limit": 2,
 "request_id": "1d378f1e-a917-42d7-9ade-ef6de1133093",
 "streams": [
  {
   "publish_domain": "jtspy.gstscc.cn",
   "app": "live",
   "stream": "123456789",
   "start_time": "2021-03-22T09:28:57Z",
   "video_codec": "H264",
   "audio_codec": "AAC",
   "video_frame_rate": 30,
   "audio_frame_rate": 43,
   "video_bitrate": 2454,
   "audio_bitrate": 156,
   "resolution": "1280x720",
   "client_ip": "183.62.48.252"
  },
  {
   "publish_"[truncated 330 chars]; line: 7, column: 13] (through reference chain: com.huaweicloud.sdk.live.v1.model.ListLiveStreamsOnlineResponse["streams"])
	at com.huaweicloud.sdk.core.utils.JsonUtils.toObjectIgnoreUnknown(JsonUtils.java:259)
	at com.huaweicloud.sdk.core.HcClient.extractResponse(HcClient.java:246)
	at com.huaweicloud.sdk.core.HcClient.syncInvokeHttp(HcClient.java:124)
	at com.huaweicloud.sdk.live.v1.LiveClient.listLiveStreamsOnline(LiveClient.java:93)
	at cn.xqrcloud.huawei.ListLiveStreamsOnlineSolution.main(ListLiveStreamsOnlineSolution.java:41)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.huaweicloud.sdk.live.v1.model.OnlineInfo` out of START_ARRAY token
 at [Source: (String)"{
 "total_num": 2,
 "total_page": 1,
 "offset": 0,
 "limit": 2,
 "request_id": "1d378f1e-a917-42d7-9ade-ef6de1133093",
 "streams": [
  {
   "publish_domain": "jtspy.gstscc.cn",
   "app": "live",
   "stream": "123456789",
   "start_time": "2021-03-22T09:28:57Z",
   "video_codec": "H264",
   "audio_codec": "AAC",
   "video_frame_rate": 30,
   "audio_frame_rate": 43,
   "video_bitrate": 2454,
   "audio_bitrate": 156,
   "resolution": "1280x720",
   "client_ip": "183.62.48.252"
  },
  {
   "publish_"[truncated 330 chars]; line: 7, column: 13] (through reference chain: com.huaweicloud.sdk.live.v1.model.ListLiveStreamsOnlineResponse["streams"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1468)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1242)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1190)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:604)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:190)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.huaweicloud.sdk.core.utils.JsonUtils.toObjectIgnoreUnknown(JsonUtils.java:256)
	... 4 common frames omitted
200
null
{
 "total_num": 2,
 "total_page": 1,
 "offset": 0,
 "limit": 2,
 "request_id": "1d378f1e-a917-42d7-9ade-ef6de1133093",
 "streams": [
  {
   "publish_domain": "jtspy.gstscc.cn",
   "app": "live",
   "stream": "123456789",
   "start_time": "2021-03-22T09:28:57Z",
   "video_codec": "H264",
   "audio_codec": "AAC",
   "video_frame_rate": 30,
   "audio_frame_rate": 43,
   "video_bitrate": 2454,
   "audio_bitrate": 156,
   "resolution": "1280x720",
   "client_ip": "183.62.48.252"
  },
  {
   "publish_domain": "jtspy.gstscc.cn",
   "app": "live",
   "stream": "lijin1",
   "start_time": "2021-03-22T09:30:19Z",
   "video_codec": "H264",
   "audio_codec": "",
   "video_frame_rate": 25,
   "audio_frame_rate": 0,
   "video_bitrate": 1000,
   "audio_bitrate": 0,
   "resolution": "1920x1080",
   "client_ip": "183.62.48.252"
  }
 ]
}
ServerResponseException {
    httpStatusCode: 200
    errorCode: null
    errorMsg: {
     "total_num": 2,
     "total_page": 1,
     "offset": 0,
     "limit": 2,
     "request_id": "1d378f1e-a917-42d7-9ade-ef6de1133093",
     "streams": [
      {
       "publish_domain": "jtspy.gstscc.cn",
       "app": "live",
       "stream": "123456789",
       "start_time": "2021-03-22T09:28:57Z",
       "video_codec": "H264",
       "audio_codec": "AAC",
       "video_frame_rate": 30,
       "audio_frame_rate": 43,
       "video_bitrate": 2454,
       "audio_bitrate": 156,
       "resolution": "1280x720",
       "client_ip": "183.62.48.252"
      },
      {
       "publish_domain": "jtspy.gstscc.cn",
       "app": "live",
       "stream": "lijin1",
       "start_time": "2021-03-22T09:30:19Z",
       "video_codec": "H264",
       "audio_codec": "",
       "video_frame_rate": 25,
       "audio_frame_rate": 0,
       "video_bitrate": 1000,
       "audio_bitrate": 0,
       "resolution": "1920x1080",
       "client_ip": "183.62.48.252"
      }
     ]
    }
    requestId: 4267f8c12ea7aa8625e88244ec0e6b8b
}
	at com.huaweicloud.sdk.core.HcClient.extractResponse(HcClient.java:277)
	at com.huaweicloud.sdk.core.HcClient.syncInvokeHttp(HcClient.java:124)
	at com.huaweicloud.sdk.live.v1.LiveClient.listLiveStreamsOnline(LiveClient.java:93)
	at cn.xqrcloud.huawei.ListLiveStreamsOnlineSolution.main(ListLiveStreamsOnlineSolution.java:41)

**Comment by Huaweicloud-SDK** [comment]
你好，这个问题在3.0.38-rc版本中已经解决了，请您使用较新的版本后确认是否可用。

点此查看 [变更日志](https://github.com/huaweicloud/huaweicloud-sdk-java-v3/blob/master/CHANGELOG_CN.md#3038-rc-2021-03-26) 。
