### ISSUE TITLE
使用物联网客户端调取删除设备，因为返回的消息体为空，导致空指针异常bug

### ISSUE THREAD

**Issue by white-alum** [huaweicloud/huaweicloud-sdk-java-v3#9]
```java
    public String delDeviceById(String deviceId){
        //获取客户端
        IoTDAClient client = getApiClientService.getClientInstance();
        //建立请求信息
        DeleteDeviceRequest request = new DeleteDeviceRequest();
        request.setDeviceId(deviceId);
        //创建请求
        //请求返回体为空，要获取结果时会有空指针异常
        DeleteDeviceResponse response  = client.deleteDevice(request);
        return null；
}
```
java.lang.NullPointerException
	at com.huaweicloud.sdk.core.impl.DefaultHttpResponse.getContentType(DefaultHttpResponse.java:67)
	at com.huaweicloud.sdk.core.HcClient.extractResponse(HcClient.java:234)
	at com.huaweicloud.sdk.core.HcClient.syncInvokeHttp(HcClient.java:115)

源码部分是这样的，强制获取响应体？
```java
    public String getContentType() {
        return this.response.body().contentType().toString();
    }
```
爱好者，非专业人士，也不知道这个是不是bug

**Comment by xionghao-hw** [comment]
是bug，3.0.7版本修复，感谢提单
